services:
  database:
    image: postgres:12
    container_name: POSTGRES
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSOWORD=test
      - POSTGRES_DB=test
    volumes:
      - ./test_volumes:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4 
    ports:
      - 1000:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - database